### ISSUE TITLE
Update for SKSE 2.0.17 needed

### ISSUE THREAD

**Issue by despotak** [Ryan-rsm-McKenzie/FlatMapMarkersSSE#1]
On 21 November 2019 Skyrim SE was updated to version `1.5.97` and a new SKSE build (`2.0.17`) is out.

Due to the `switch` below, we need an update
https://github.com/Ryan-rsm-McKenzie/FlatMapMarkersSSE/blob/cd250f708fd0b4d27ad07b2943d172664bbbf865/src/main.cpp#L49-L52

Thank you very much for your time.

**Comment by Ryan-rsm-McKenzie** [comment]
The mod being out of date is not a bug. Don't abuse this page.
